eureka:
  client:
    register-with-eureka: false
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: joueurs-service
          uri: http://localhost:8080
          predicates:
            - Path=/joueurs/**
      discovery:
        locator:
          lower-case-service-id: true
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8222
